### ISSUE TITLE
幻獸帕魯開設伺服器功能新增-設定密碼2024.02.06

### ISSUE THREAD

**Issue by a879591921** [Dalufishe/palserver-GUI#1]
希望能在下圖兩處, 建立伺服器, 伺服器設定, 增加伺服器密碼設定更改功能=)

再次謝謝樓主開發這麼好用的工具, 感恩大德

**Comment by Dalufishe** [comment]
好的 收到
然後 你的 ip 位置暴露了 😳
剛好提醒到我應該做一個 ip 隱藏 / 顯示 感謝！

**Comment by a879591921** [comment]
感謝大大 已經實裝 非常好用 咖啡奉上>"<
