### ISSUE TITLE
伺服器更新完畢彈窗導致無法編輯或建立伺服器

### ISSUE THREAD

**Issue by LilaS-tw** [Dalufishe/palserver-GUI#3]
伺服器更新完畢彈窗
![image](https://github.com/Dalufishe/palserver-GUI/assets/9333314/20fd2828-c6f6-4485-abaa-2a6901aca673)
無法編輯伺服器欄位內容
![image](https://github.com/Dalufishe/palserver-GUI/assets/9333314/ddb6081a-d93e-4a95-af76-98b89d1c2eb3)
無法輸入建立伺服器欄位內容
![image](https://github.com/Dalufishe/palserver-GUI/assets/9333314/c14b3b2b-b9f8-46aa-92b9-dd97d6be1cd3)
必須透過以下方式才會恢復正常:
1. 更改世界設定→從原始文件編輯(彈出記事本視窗)
2. 開啟存檔位置→開啟伺服器資料夾(彈出資料夾視窗)
3. 關閉重開

**Comment by Dalufishe** [comment]
感謝回報問題，會在之後的版本修正

**Comment by Dalufishe** [comment]
好怪喔 我這邊是正常耶XD

**Comment by LilaS-tw** [comment]
我在虛擬機或是本機上測試都會有這個問題，不過切換其他視窗再切回去就可以正常編輯了
我先關閉issue好了
