### ISSUE TITLE
升级1.0.4之后一直卡在系统安装进行中

### ISSUE THREAD

**Issue by TwenYounG** [Dalufishe/palserver-GUI#30]
![image](https://github.com/Dalufishe/palserver-GUI/assets/7163148/55aac2ac-8a77-4517-b975-d60067711fa1)
一直停留在这个界面

**Comment by Dalufishe** [comment]
應該是因為我使用 gcp 存版本資訊 忘記做錯誤處理。你如果在中國裝一下 vpn 再執行下載。

**Comment by TwenYounG** [comment]
> 應該是因為我使用 gcp 存版本資訊 忘記做錯誤處理。你如果在中國裝一下 vpn 再執行下載。

OK，解决了

**Comment by GitHub-No1** [comment]
> 應該是因為我使用 gcp 存版本資訊 忘記做錯誤處理。你如果在中國裝一下 vpn 再執行下載。

你好，首先感謝開發了這麽好的軟件。因為我在中國大陸使用程序，掛VPN特別不便，可否更新一個不用掛VPN的補丁？萬分感謝！

**Comment by Dalufishe** [comment]
@GitHub-No1 好的，之後版本加上。另外您可以先使用 1.0.3 版本，並不需要使用 VPN 取而代之是每次開始應用都會到 steamcmd 執行下載驗證。

**Comment by GitHub-No1** [comment]
> @GitHub-No1 好的，之後版本加上。另外您可以先使用 1.0.3 版本，並不需要使用 VPN 取而代之是每次開始應用都會到 steamcmd 執行下載驗證。

OK，再次感谢！静等之後版本更新。生活愉快！
