### ISSUE TITLE
希望能夠在控制台新增一些功能

### ISSUE THREAD

**Issue by 1476523** [Dalufishe/palserver-GUI#7]
希望新增
"關閉伺服器" 按鈕
關閉伺服器等待的 "秒數"
關閉伺服器的 "訊息"
這對應伺服器指令 /Shutdown <秒數> <訊息文字>

另外也希望新增
顯示 "玩家資訊"
這對應伺服器指令 /ShowPlayers
伺服器廣播訊息發送
這對應伺服器指令 /Broadcast <MessageText>
踢出或禁止玩家
這對應伺服器指令
踢出 /KickPlayer <SteamID>
禁止 /BanPlayer <SteamID>

以上只是希望新增的功能
如果無法實現也沒關係
主要是讓伺服器的擁有者無須開啟遊戲就可方便管理
官方指令
https://tech.palworldgame.com/settings-and-operation/commands

**Comment by Dalufishe** [comment]
我將這些列進 todolist 了, 之後更新, haha
